<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <title>Async Await</title>
    <link rel="stylesheet" href="../base.css">
</head>

<body>
    <script>
        function wait(ms = 0) {
            return new Promise((resolve) => {
                setTimeout(resolve, ms);
            })
        }

        function makePizza(toppings = []) {
            return new Promise(function (resolve, reject) {
                // reject if people try with pineapple
                if (toppings.includes('pineapple')) {
                    reject('Seriously? Get out üçç');
                }
                const amountOfTimeToBake = 500 + (toppings.length * 200);
                // wait 1 second for the pizza to cook:
                setTimeout(function () {
                    // when you are ready, you can resolve this promise
                    resolve(`Here is your pizza üçï with the toppings ${toppings.join(' ')}`);
                }, amountOfTimeToBake);
                // if something went wrong, we can reject this promise;
            });
        }

        // async function go(){
        //     try{

        //         const pizza = await makePizza('pineapple');

        //     }catch(err){
        //         console.log('ohhh nooo!!');
        //         console.log(err);
        //     }

        // }
        function handleError(err){
            console.log('ohhh nooo!!');
            console.log(err);
        }
        //or
        async function go(){  
            const pizza = await makePizza('pineapple').catch(handleError);
            console.log(pizza);
        }

        async function go(){  
            const pizza = await makePizza('pineapple');
            console.log(pizza);
            return pizza;
        }

       

        go().catch(handleError);


        //make a safe function with a HOF higher order funciton 
        function makeSafe(fn,errorHandler){
            return funciton(){
                fn.catch(errorHandler);
            }
        }

        go();// not safe

        const  safeGo = makeSafe(go, handleError);

        safeGo();
        
    </script>
</body>

</html>
